### PR TITLE
Write temporary files to local directory by default

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
This fixes a build problem on one of my virtual machines which has only 1.9 GB free in the root filesystem (and so in `/tmp`, too), but provides a large volume for `/HOME` with my user data and 25 GB free disk space.

**Comment by kba** [comment]
I concur with @bertsky, let's make this optional and default to `/tmp` so you CAN do

```sh
d=$(mktemp -d -p $PWD) && \
make ocrd-anybaseocr-crop TMPDIR="$d" && \
rm -rf -- "$d"
```

but do not HAVE to set TMPDIR explicitly

**Comment by stweil** [comment]
I used `TMPDIR=$PWD/tmp make all` successfully without this patch, so this modifications just makes life a little bit easier for me.

**Comment by bertsky** [comment]
> I used `TMPDIR=$PWD/tmp make all` successfully without this patch, so this modifications just makes life a little bit easier for me.

Then I'd say just put `export TMPDIR=path/to/ocrd_all/tmp` in your `~/.bashrc` or in `venv/bin/activate` and you're good. (We should still add this remark to `make help` and README, though.)

**Comment by kba** [comment]
I added a paragraph to the README on this.

**Comment by kba** [comment]
Can you cherry pick https://github.com/UB-Mannheim/ocrd_all/commit/984863617fb23c834aeeb18d55b8573a040273cb to master though?

**Comment by stweil** [comment]
Already done. I also fixed a typo, so you will get a local conflict.

**Pull request closed without merging**
